// ── tailwind.config.ts ──
import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-deep': 'var(--color-surface-deep)',
        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        accent: 'var(--color-accent)',
        'accent-dark': 'var(--color-accent-dark)',
        rust: 'var(--color-rust)',
        muted: 'var(--color-muted)',
        card: 'var(--color-card)',
        line: 'var(--color-line)',
        'bg-soft': 'var(--color-bg-soft)',
        'dark-text': 'var(--color-dark-text)',
        'dark-text-secondary': 'var(--color-dark-text-secondary)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        dark: 'var(--color-dark)',
        'dark-raised': 'var(--color-dark-raised)',
        'dark-border': 'var(--color-dark-border)',
      },
      fontFamily: {
        serif: ['var(--font-jost)', 'system-ui', 'sans-serif'],
        display: ['var(--font-jost)', 'system-ui', 'sans-serif'],
        body: ['var(--font-jost)', 'system-ui', 'sans-serif'],
        script: ['var(--font-script)', 'cursive'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1rem' }],
        xs: ['0.75rem', { lineHeight: '1.1rem' }],
        sm: ['0.875rem', { lineHeight: '1.4rem' }],
        base: ['1rem', { lineHeight: '1.7rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.7rem' }],
        '2xl': ['1.5rem', { lineHeight: '1.3' }],
        '3xl': ['1.875rem', { lineHeight: '1.2' }],
        '4xl': ['2.25rem', { lineHeight: '1.12' }],
        '5xl': ['3rem', { lineHeight: '1.06' }],
        '6xl': ['3.75rem', { lineHeight: '1.02' }],
        '7xl': ['4.5rem', { lineHeight: '0.98' }],
        '8xl': ['6rem', { lineHeight: '0.95' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
        '42': '10.5rem',
      },
      letterSpacing: {
        tightish: '-0.02em',
        wide: '0.08em',
        label: '0.22em',
        widest: '0.25em',
      },
      borderRadius: {
        none: '0',
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      maxWidth: {
        prose: '62ch',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out-soft': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        '250': '250ms',
        '400': '400ms',
        '600': '600ms',
      },
      boxShadow: {
        card: '0 1px 2px rgba(26, 24, 22, 0.04), 0 8px 30px -12px rgba(26, 24, 22, 0.14)',
        'card-hover': '0 2px 4px rgba(26, 24, 22, 0.06), 0 20px 48px -16px rgba(26, 24, 22, 0.22)',
        soft: '0 1px 3px rgba(26, 24, 22, 0.06)',
      },
      screens: {
        xs: '480px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}

export default config
